version: '2.1'

services:
  squid-gcp-proxy:
    image: "mesoform/concierge-squid-gcp-proxy:0.1.0"
    domainname: "squid-gcp-proxy.gcpservices.mesoform.com"
    dns_search:
      - squid-gcp-proxy.gcp.mesoform.com
      - apache-fwdproxy.gcpservices.mesoform.com
      - svc.ops.mesoform-services.com
    labels:
      - triton.cns.services=squid-gcp-proxy
    restart: always
    mem_limit: 128m
    ## For Triton bridge mode needs explicitly setting because the docker compose client
    ## sends network_mode=default by default. The uncommenting of this line is handled
    ## in the Ansible code but can obviously be uncommented personally for manual interaction
    # network_mode: bridge
    # env_file: _env
    depends_on:
      - consul
    environment:
      - EM_SERVER=zbxserver
      - SVC_DISCOVERY=consul:8301
      - ENV_VAR=TRUE
    ## uncomment to test your application start without containerpilot
    #entrypoint: /usr/sbin/squid3 -f /etc/squid-gcp-proxy/squid.conf

