## This is a compose file to define any integrations for our Concierge Managed Application.
## It is concatenated with the main docker-compose.yml file
## already created for our application. See tasks/start_orchestration.yml
## http://www.mesoform.com/blog-listing/info/the-concierge-paradigm

version: '2.1'
services:
  consul:
    image: "mesoform/concierge-consul:devtest"
    domainname: "consul.oaas.mesoform.com"
    dns_search:
      - apache-fwdproxy.gcpservices.mesoform.com
      - svc.ops.mesoform-services.com
    labels:
      - triton.cns.services=consul
    restart: always
    mem_limit: "128m"
    ## For Triton bridge mode needs explicitly setting because the docker compose client
    ## sends network_mode=default by default. The uncommenting of this line is handled
    ## in the Ansible code but can obviously be uncommented personally for manual interaction
    # network_mode: bridge
    # env_file: _env
    ports:
      - 8301
      - 8300
      - 8400
      - 8302
      - 8500
    environment:
      - CONSUL=consul
      - SVC_DISCOVERY=consul:8301
      - EM_SERVER=zbxserver

  mysql:
    image: "mesoform/concierge-mysql:devtest"
    domainname: "mysql.oaas.mesoform.com"
    labels:
      - triton.cns.services=mysql
    restart: always
    mem_limit: 1g
    ## For Triton bridge mode needs explicitly setting because the docker compose client
    ## sends network_mode=default by default. The uncommenting of this line is handled
    ## in the Ansible code but can obviously be uncommented personally for manual interaction
    # network_mode: bridge
    env_file: _env
    depends_on:
      - consul
    links:
      - consul
    expose:
      - '3306'
    environment:
      - LOG_LEVEL=DEBUG
      - SERVICE_NAME=mysql
      - EM_SERVER=zbxserver

  zbxserver:
    image: "mesoform/concierge-zabbix:devtest"
    domainname: "zabbix.oaas.mesoform.com"
    labels:
      - triton.cns.services=zbxserver
    restart: always
    mem_limit: 128m
    ## For Triton bridge mode needs explicitly setting because the docker compose client
    ## sends network_mode=default by default. The uncommenting of this line is handled
    ## in the Ansible code but can obviously be uncommented personally for manual interaction
    # network_mode: bridge
    # env_file: _env
    depends_on:
      - consul
      - mysql
    links:
      - consul
      - mysql
    ports:
      - 10051
      - 10051/tcp
    environment:
      DB_SERVER_HOST: "mysql"
      MYSQL_DATABASE: "zabbix"
      MYSQL_USER: "zabbix"
      MYSQL_PASSWORD: "zbxusrpwd"
      EM_SERVER: "zbxserver"
      ZBX_USER: "Admin"
      ZBX_PASS: "zabbix"
      ZBX_API_HOST: "172.18.0.5"
      ZBX_CONFIG_DIR: "/usr/lib/zabbix/app_config"
      ZBX_DEBUGLEVEL: "3"
      ZBX_CACHESIZE: "64M"
      DOCKER_HOST: "tcp://dockerapi:1234"

  zbxweb:
    image: "mesoform/concierge-zabbix-web:devtest"
    domainname: "zabbix-web.oaas.mesoform.com"
    labels:
      - triton.cns.services=zbxweb
    restart: always
    mem_limit: 512m
    ## For Triton bridge mode needs explicitly setting because the docker compose client
    ## sends network_mode=default by default. The uncommenting of this line is handled
    ## in the Ansible code but can obviously be uncommented personally for manual interaction
    # network_mode: bridge
    # env_file: _env
    depends_on:
      - consul
      - mysql
      - zbxserver
    links:
      - consul
      - mysql
      - zbxserver
    ports:
      - 80
      - 443
    environment:
      ZBX_SERVER_HOST: "zbxserver"
      ZBX_SERVER_NAME: "zabbix-mesoform"
      EM_SERVER: "zbxserver"
      DB_SERVER_HOST: "mysql"
      MYSQL_DATABASE: "zabbix"
      MYSQL_USER: "zabbix"
      MYSQL_PASSWORD: "zbxusrpwd"
      TZ: "UTC"

  dockerapi:
    container_name: "dockerapi"
    image: "bobrik/socat"
    mem_limit: "64m"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    expose:
      - 1234
    command: TCP-LISTEN:1234,fork UNIX-CONNECT:/var/run/docker.sock
    depends_on:
      - zbxweb